### ISSUE TITLE
Article: Effective Team Communication

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/knowledge-base-content#103]

**Comment by zeman-j4** [comment]
What this is about: In order to get teams working as well-oiled machines it is important to establish healthy communication that is effective and courteous. Removing communication blocks leads to happier developers, healthy environment and removes frustration.

You can start your research here: https://blog.jostle.me/blog/how-to-easily-get-effective-team-communication
https://www.proofhub.com/articles/effective-communication

Contribution guide: https://github.com/DXHeroes/knowledge-base-content/blob/master/CONTRIBUTING.md

**Comment by ng29** [comment]
@prokopsimek   / @ridlees  / @zeman-j4 

Can. i pick this up ? ?

**Comment by CodeLeom** [comment]
Can I get tis assigned to me?

**Comment by prokopsimek** [comment]
@CodeLeom Still interested?

**Comment by CodeLeom** [comment]
@prokopsimek yes, I am interested
