### ISSUE TITLE
Article: Unnecessary functions

### ISSUE THREAD

**Issue by prokopsimek** [DXHeroes/knowledge-base-content#156]

**Comment by ridlees** [comment]
What is this about: Unnecessary functions are your team problem. They waste resources, bloat your code, and can lead to unsuccessful products. They are mostly caused by bad product design. 
Read more here: https://techbeacon.com/app-dev-testing/why-unnecessary-variables-are-bad-your-code, https://www.valueanalysis.ca/fast.php, https://www.bruschitech.com/blog/what-is-value-analysis-value-engineering, 
Contribution guide: https://github.com/DXHeroes/knowledge-base-content/blob/master/CONTRIBUTING.md

**Comment by Ruchika30** [comment]
I would like to take this up @prokopsimek

**Comment by ridlees** [comment]
Hello @Ruchika30, I am deeply sorry for the delay. Unfortunately, there is already a PR that closes this issue. You could help with the text review if you have an interest in this topic. Alternatively, look at the other issues (https://github.com/DXHeroes/knowledge-base-content/issues)
