### ISSUE TITLE
How API-first development impacts software development methods

### ISSUE THREAD

**Issue by D-stevpm** [DXHeroes/knowledge-base-content#397]
# Title: How API-first development impacts software development methods

- [ ] What is this about: “ This article talks about why it is important to consider API first approach in building APIs. The practices solve a problem that relates it why you need to talk to users why building API products and make sure your product is solving core needs for your business. 

- [ ] Read more here: The starting point for your research (You can use different sources if you have better ones)

- [ ] Pick the corresponding labels: 
    - Stage:research
  

## How to contribute:
- Follow our [Contribution guide](https://github.com/DXHeroes/knowledge-base-content/blob/master/CONTRIBUTING.md)
- How to [Git and Pull Requests]( https://github.com/firstcontributions/first-contributions/blob/master/README.md)
- How to [Markdown](https://guides.github.com/features/mastering-markdown/), [Markdown interactive demo](https://www.markdowntutorial.com/lesson/1/) or [Google Docs Addon](https://gsuite.google.com/marketplace/app/docs_to_markdown/700168918607)

**Comment by prokopsimek** [comment]
@D-stevpm Brilliant topic! Could we make the article title sound more like a best practice in software development rather than just talking about the importance of considering an API-first approach in building APIs? Something like "API-first" or "API-first development" could convey the same message while also emphasizing the best practice aspect.

**Comment by D-stevpm** [comment]
Alright, API-first development sounds a lot better

**Comment by prokopsimek** [comment]
Go for it! 🙌
